# Generated by Django 2.2 on 2020-07-03 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=1000)),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=100, null=True)),
                ('queriedAt', models.DateTimeField(default=datetime.datetime(2020, 7, 3, 6, 2, 34, 105694, tzinfo=utc))),
                ('results', models.ManyToManyField(to='news.QueryResult')),
            ],
        ),
    ]
