# Generated by Django 2.2 on 2020-07-03 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queriedAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 6, 2, 56, 959135, tzinfo=utc)),
        ),
    ]
