# Generated by Django 2.2 on 2020-07-04 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200705_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='queriedAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 2, 19, 15, 958461, tzinfo=utc)),
        ),
    ]
